from enum import Enum, auto


class ErrorCode(Enum):
    """MOVEMENT ERRORS"""
    DEPLETED_INSIDE_TILES = auto()
    DEPLETED_OUTSIDE_TILES = auto()
    INVALID_POSITION = auto()
    INVALID_ACTION_ROTATE_LOCKED_TILE = auto()
    INVALID_MOVE_OUT_OF_BOUNDS = auto()
    INVALID_MOVE_NO_DOOR = auto()
    INVALID_MOVE_ACROSS_AREAS = auto()
    INVALID_MOVE_FLEE_TO_UNKNOWN_TILE = auto()
    INVALID_MOVE_ZOMBIE_DOOR_TO_KNOWN_TILE = auto()
    INVALID_MODE_MOVEMENT = auto()
    INVALID_MODE_ROTATE_TILE = auto()
    INVALID_MODE_LOCK_TILE = auto()
    INVALID_VALUE_GAME_MODE = auto()
    INVALID_VALUE_DIRECTION = auto()
    INVALID_VALUE_MAP_DIMENSION = auto()
    INVALID_VALUE_STARTING_POSITION = auto()
    INVALID_TYPE_MAP_DIMENSION = auto()
    INVALID_TYPE_STARTING_POSITION = auto()
    INVALID_TYPE_RANDOMIZER_SEED = auto()
    FATAL_UNPLACEABLE_TILE = auto()

    """GENERAL ERRORS"""
    FATAL_ERROR = auto()